' run with cscript
if instr(lcase(WScript.FullName),"cscript")=0 Then
	WScript.Echo("Please run:  cscript /nologo testall.vbs")
	WScript.Quit
end if

' create shell object
set WshShell=WScript.CreateObject("WScript.Shell")

WshShell.Exec(PREFIX & "bytebuffer")
WshShell.Exec(PREFIX & "bytestring")
WshShell.Exec(PREFIX & "character")
WshShell.Exec(PREFIX & "charstring")
WshShell.Exec(PREFIX & "commandline")
WshShell.Exec(PREFIX & "crypt")
WshShell.Exec(PREFIX & "datetime")
WshShell.Exec(PREFIX & "dictionary")
WshShell.Exec(PREFIX & "directory")
WshShell.Exec(PREFIX & "dynamicarray")
WshShell.Exec(PREFIX & "dynamiclib")
WshShell.Exec(PREFIX & "environment")
WshShell.Exec(PREFIX & "error")
WshShell.Exec(PREFIX & "file")
WshShell.Exec(PREFIX & "groupentry")
WshShell.Exec(PREFIX & "handoff")
WshShell.Exec(PREFIX & "hostentry")
WshShell.Exec(PREFIX & "linkedlist")
WshShell.Exec(PREFIX & "listener")
WshShell.Exec(PREFIX & "logger")
WshShell.Exec(PREFIX & "memorymap")
WshShell.Exec(PREFIX & "memorypool")
WshShell.Exec(PREFIX & "parameterstring")
WshShell.Exec(PREFIX & "permissions")
WshShell.Exec(PREFIX & "process")
WshShell.Exec(PREFIX & "protocolentry")
WshShell.Exec(PREFIX & "randomnumber")
WshShell.Exec(PREFIX & "regularexpression")
WshShell.Exec(PREFIX & "semaphoreset")
WshShell.Exec(PREFIX & "serviceentry")
WshShell.Exec(PREFIX & "sharedmemory")
WshShell.Exec(PREFIX & "signal")
WshShell.Exec(PREFIX & "singlylinkedlist")
WshShell.Exec(PREFIX & "snooze")
WshShell.Exec(PREFIX & "staticarray")
WshShell.Exec(PREFIX & "stringbuffer")
WshShell.Exec(PREFIX & "sys")
WshShell.Exec(PREFIX & "thread")
WshShell.Exec(PREFIX & "threadmutex")
WshShell.Exec(PREFIX & "url")
WshShell.Exec(PREFIX & "userentry")
WshShell.Exec(PREFIX & "xmldom")
WshShell.Exec(PREFIX & "csvdom")
WshShell.Exec(PREFIX & "jsondom")
WshShell.Exec(PREFIX & "inidom")
WshShell.Exec(PREFIX & "propdom")
WshShell.Exec(PREFIX & "mvcproperties")
