top_builddir = ..

include ../config.mk

all:

install:
	$(MKINSTALLDIRS) $(docdir)
	$(MKINSTALLDIRS) $(docdir)/css
	$(MKINSTALLDIRS) $(docdir)/classes/html
	$(MKINSTALLDIRS) $(docdir)/features
	$(MKINSTALLDIRS) $(docdir)/programming
	$(MKINSTALLDIRS) $(docdir)/images
	$(CP) installing.html $(docdir)
	$(CP) index.html $(docdir)
	$(CP) css/styles.css $(docdir)/css
	$(CP) classes/html/a*.html $(docdir)/classes/html
	$(CP) classes/html/b*.html $(docdir)/classes/html
	$(CP) classes/html/c*.html $(docdir)/classes/html
	$(CP) classes/html/d*.html $(docdir)/classes/html
	$(CP) classes/html/e*.html $(docdir)/classes/html
	$(CP) classes/html/f*.html $(docdir)/classes/html
	$(CP) classes/html/g*.html $(docdir)/classes/html
	$(CP) classes/html/h*.html $(docdir)/classes/html
	$(CP) classes/html/i*.html $(docdir)/classes/html
	$(CP) classes/html/j*.html $(docdir)/classes/html
	$(CP) classes/html/l*.html $(docdir)/classes/html
	$(CP) classes/html/m*.html $(docdir)/classes/html
	$(CP) classes/html/n*.html $(docdir)/classes/html
	$(CP) classes/html/o*.html $(docdir)/classes/html
	$(CP) classes/html/p*.html $(docdir)/classes/html
	$(CP) classes/html/r*.html $(docdir)/classes/html
	$(CP) classes/html/s*.html $(docdir)/classes/html
	$(CP) classes/html/t*.html $(docdir)/classes/html
	$(CP) classes/html/u*.html $(docdir)/classes/html
	$(CP) classes/html/w*.html $(docdir)/classes/html
	$(CP) classes/html/x*.html $(docdir)/classes/html
	$(CP) classes/html/*.png $(docdir)/classes/html
	$(CP) classes/html/*.css $(docdir)/classes/html
	$(CP) classes/html/*.js $(docdir)/classes/html
	$(CP) features/*.html $(docdir)/features
	$(CP) programming/*.html $(docdir)/programming
	$(CP) images/*.png $(docdir)/images
	$(CHMOD) 644 $(docdir)/*.html
	$(CHMOD) 644 $(docdir)/css/*
	$(CHMOD) 644 $(docdir)/classes/html/a*.html
	$(CHMOD) 644 $(docdir)/classes/html/b*.html
	$(CHMOD) 644 $(docdir)/classes/html/cg*.html
	$(CHMOD) 644 $(docdir)/classes/html/ch*.html
	$(CHMOD) 644 $(docdir)/classes/html/classa*.html
	$(CHMOD) 644 $(docdir)/classes/html/classb*.html
	$(CHMOD) 644 $(docdir)/classes/html/classc*.html
	$(CHMOD) 644 $(docdir)/classes/html/classd*.html
	$(CHMOD) 644 $(docdir)/classes/html/classe*.html
	$(CHMOD) 644 $(docdir)/classes/html/classf*.html
	$(CHMOD) 644 $(docdir)/classes/html/classg*.html
	$(CHMOD) 644 $(docdir)/classes/html/classh*.html
	$(CHMOD) 644 $(docdir)/classes/html/classi*.html
	$(CHMOD) 644 $(docdir)/classes/html/classj*.html
	$(CHMOD) 644 $(docdir)/classes/html/classl*.html
	$(CHMOD) 644 $(docdir)/classes/html/classm*.html
	$(CHMOD) 644 $(docdir)/classes/html/classn*.html
	$(CHMOD) 644 $(docdir)/classes/html/classo*.html
	$(CHMOD) 644 $(docdir)/classes/html/classp*.html
	$(CHMOD) 644 $(docdir)/classes/html/classr*.html
	$(CHMOD) 644 $(docdir)/classes/html/classs*.html
	$(CHMOD) 644 $(docdir)/classes/html/classt*.html
	$(CHMOD) 644 $(docdir)/classes/html/classu*.html
	$(CHMOD) 644 $(docdir)/classes/html/classw*.html
	$(CHMOD) 644 $(docdir)/classes/html/classx*.html
	$(CHMOD) 644 $(docdir)/classes/html/cli*.html
	$(CHMOD) 644 $(docdir)/classes/html/co*.html
	$(CHMOD) 644 $(docdir)/classes/html/cr*.html
	$(CHMOD) 644 $(docdir)/classes/html/cs*.html
	$(CHMOD) 644 $(docdir)/classes/html/d*.html
	$(CHMOD) 644 $(docdir)/classes/html/e*.html
	$(CHMOD) 644 $(docdir)/classes/html/f*.html
	$(CHMOD) 644 $(docdir)/classes/html/g*.html
	$(CHMOD) 644 $(docdir)/classes/html/h*.html
	$(CHMOD) 644 $(docdir)/classes/html/i*.html
	$(CHMOD) 644 $(docdir)/classes/html/j*.html
	$(CHMOD) 644 $(docdir)/classes/html/l*.html
	$(CHMOD) 644 $(docdir)/classes/html/m*.html
	$(CHMOD) 644 $(docdir)/classes/html/n*.html
	$(CHMOD) 644 $(docdir)/classes/html/o*.html
	$(CHMOD) 644 $(docdir)/classes/html/p*.html
	$(CHMOD) 644 $(docdir)/classes/html/r*.html
	$(CHMOD) 644 $(docdir)/classes/html/s*.html
	$(CHMOD) 644 $(docdir)/classes/html/t*.html
	$(CHMOD) 644 $(docdir)/classes/html/u*.html
	$(CHMOD) 644 $(docdir)/classes/html/w*.html
	$(CHMOD) 644 $(docdir)/classes/html/x*.html
	$(CHMOD) 644 $(docdir)/classes/html/*.png
	$(CHMOD) 644 $(docdir)/classes/html/*.css
	$(CHMOD) 644 $(docdir)/classes/html/*.js
	$(CHMOD) 644 $(docdir)/features/*.html
	$(CHMOD) 644 $(docdir)/programming/*.html
	$(CHMOD) 644 $(docdir)/images/*

uninstall:
	$(RMTREE) $(docdir)
