// Copyright (c) David Muse
// See the COPYING file for more information.

#ifndef RUDIMENTS_DH_H
#define RUDIMENTS_DH_H

#include <rudiments/private/dhincludes.h>

/** dh errors */
enum dherror_t {
	DH_ERROR_SUCCESS=0,
	DH_ERROR_NULL,
	DH_ERROR_INVALID_PARAMETERS,
	DH_ERROR_GENERATE_KEYS_FAILED,
	DH_ERROR_GENERATE_SECRET_FAILED,
	DH_ERROR_UNSUPPORTED
};

/** The DH class provides a simple Diffie-Hellman implementation. */
class RUDIMENTS_DLLSPEC dh {
	public:
		/** Creates an instance of the dh class. */
		dh();

		/** Deletes this instance of the dh class. */
		virtual	~dh();

		/** Sets the prime modulus to "dhp" of "dhpsize" bytes. */
		void	setPrimeModulus(const byte_t *dhp, size_t dhpsize);

		/** Returns the prime modulus set by the most recent call to
		 *  setPrimeModulus() or NULL if no prime modulus has been
		 *  set. */
		const byte_t	*getPrimeModulus();

		/** Returns the number of bytes in the prime modulus set by the
		 *  most recent call to setPrimeModulus() or 0 if no prime
		 *  modulus has been set. */
		size_t	getPrimeModulusSize();

		/** Sets the generator/base to "dhg" of "dhgsize" bytes. */
		void	setGenerator(const byte_t *dhg, size_t dhgsize);

		/** Returns the genarator/base set by the most recent call to
		 *  setPrimeModulus() or NULL if no genarator/base has been
		 *  set. */
		const byte_t	*getGenerator();

		/** Returns the number of bytes in the generator/base set by
		 *  the most recent call to setPrimeModulus() or 0 if no
		 *  generator/base has been set. */
		size_t	getGeneratorSize();

		/** Generates ephemeral private and public keys.  Returns true
		 *  if key generation was successful and false otherwise. */
		bool	generateKeys();

		/** Returns the private key generated by the most recent call
		 *  to generateKeys() or NULL if generateKeys() has not been
		 *  called. */
		const byte_t	*getPrivateKey();

		/** Returns the size of the private key generated by the most
		 *  recent call to generateKeys() or NULL if generateKeys() has
		 *  not been called. */
		size_t	getPrivateKeySize();

		/** Returns the public key generated by the most recent call
		 *  to generateKeys() or NULL if generateKeys() has not been
		 *  called. */
		const byte_t	*getPublicKey();

		/** Returns the size of the public key generated by the most
		 *  recent call to generateKeys() or NULL if generateKeys() has
		 *  not been called. */
		size_t	getPublicKeySize();

		/** Sets the peer public key to "pk" of "pksize" bytes. */
		void	setPeerPublicKey(const byte_t *pk, size_t pksize);

		/** Returns the peer public key set by the most recent call to
		 *  setPeerPublicKey() or NULL if no peer public key has been
		 *  set. */
		const byte_t	*getPeerPublicKey();

		/** Returns the size of the peer public key set by the most
		 *  recent call to setPeerPublicKey() or NULL if no peer public
		 *  key has been set. */
		size_t	getPeerPublicKeySize();

		/** Generates the shared secret based on our private key and
		 *  the peer's public key.  Returns true if secret generation
		 *  was successful and false otherwise. */
		bool	generateSharedSecret();

		/** Returns the shared secret generated by the most recent call
		 *  to generateSharedSecret() or NULL if generateSharedSecret()
		 *  has not been called. */
		const byte_t	*getSharedSecret();

		/** Returns the size of the shared secret generated by the most
		 *  recent call to generateSharedSecret() or NULL if
		 *  generateSharedSecret() has not been called. */
		uint64_t	getSharedSecretSize();

		/** Returns the most recent error. */
		dherror_t	getError();

		/** Clears the shared secret, our public and private keys.
		 *
		 *  Does not clear the prime modulus or the generator.
		 *
		 *  Returns true on success or false if an error occurred. */
		bool	clear();

		/** Clears the shared secret, the peer public key, our public
		 *  and private keys, the prime modulus, and the generator.
		 *  Returns true on success or false if an error occurred. */
		bool	reset();

		/** Returns true if this platform supports dh and false
		 *  otherwise. */
		bool	isSupported();

	#include <rudiments/private/dh.h>
};

#endif
